# import pandas as pd
# import numpy as np
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.preprocessing import StandardScaler
# import pickle
# import os

# def train_model():
#     """Train the ML model to predict employee onboarding status"""
    
#     print(" Starting model training...")
    
#     # Load training data (generated by generate_dummy_data.py)
#     if not os.path.exists('training_data.csv'):
#         print(" Error: training_data.csv not found!")
#         print("Run 'python generate_dummy_data.py' first")
#         return
    
#     df = pd.read_csv('training_data.csv')
#     print(f" Loaded {len(df)} training records")
    
#     # Features for prediction
#     X = df[['completion_rate', 'days_elapsed', 'overdue_tasks', 'avg_time_per_task']]
    
#     # Target variable (what we want to predict)
#     y = df['status']
    
#     # Split data into training and testing sets (80% train, 20% test)
#     X_train, X_test, y_train, y_test = train_test_split(
#         X, y, test_size=0.2, random_state=42
#     )
    
#     # Normalize the features (scale to 0-1 range)
#     scaler = StandardScaler()
#     X_train_scaled = scaler.fit_transform(X_train)
#     X_test_scaled = scaler.transform(X_test)
    
#     # Train Random Forest Classifier
#     print(" Training Random Forest model...")
#     model = RandomForestClassifier(
#         n_estimators=100,
#         max_depth=10,
#         random_state=42
#     )
#     model.fit(X_train_scaled, y_train)
    
#     # Evaluate accuracy
#     train_accuracy = model.score(X_train_scaled, y_train)
#     test_accuracy = model.score(X_test_scaled, y_test)
    
#     print(f" Training Accuracy: {train_accuracy * 100:.2f}%")
#     print(f" Testing Accuracy: {test_accuracy * 100:.2f}%")
    
#     # Save model and scaler
#     with open('model.pkl', 'wb') as f:
#         pickle.dump(model, f)
    
#     with open('scaler.pkl', 'wb') as f:
#         pickle.dump(scaler, f)
    
#     print(" Model saved as model.pkl")
#     print(" Scaler saved as scaler.pkl")
    
#     # Show feature importance
#     feature_importance = pd.DataFrame({
#         'feature': X.columns,
#         'importance': model.feature_importances_
#     }).sort_values('importance', ascending=False)
    
#     print("\n Feature Importance:")
#     print(feature_importance.to_string(index=False))
    
#     return model, scaler

# if __name__ == '__main__':
#     train_model()

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pickle
import os

MODEL_PATH = os.path.join(os.path.dirname(__file__), "model.pkl")

def train_model():
    """Train with synthetic dummy data and save model"""

    # Synthetic training data
    # Features: [progress%, tasks_total, tasks_completed, tasks_overdue, days_since_joining]
    X = np.array([
        # on-track examples
        [90, 10, 9, 0, 10],
        [85, 8, 7, 0, 7],
        [75, 12, 9, 0, 14],
        [100, 5, 5, 0, 5],
        [80, 10, 8, 0, 12],
        [70, 6, 5, 0, 8],
        [95, 20, 19, 0, 20],
        [78, 9, 7, 0, 10],
        [82, 11, 9, 0, 15],
        [88, 7, 6, 0, 6],
        [0, 0, 0, 0, 2],   # new employee, no tasks yet
        [0, 0, 0, 0, 1],
        [60, 5, 3, 0, 5],

        # at-risk examples
        [50, 10, 5, 1, 15],
        [45, 8, 4, 1, 12],
        [55, 12, 7, 1, 18],
        [40, 10, 4, 2, 20],
        [35, 8, 3, 1, 14],
        [48, 6, 3, 1, 10],
        [52, 9, 5, 1, 16],
        [38, 10, 4, 2, 18],
        [42, 7, 3, 1, 12],
        [30, 8, 2, 2, 15],

        # delayed examples
        [20, 10, 2, 4, 25],
        [15, 8, 1, 5, 30],
        [10, 12, 1, 6, 28],
        [25, 10, 2, 3, 22],
        [5,  8, 0, 5, 20],
        [18, 9, 2, 4, 26],
        [12, 11, 1, 6, 30],
        [22, 10, 2, 4, 24],
        [8,  7, 1, 5, 28],
        [0,  6, 0, 6, 35],
    ])

    y = np.array([
        # on-track
        "on-track","on-track","on-track","on-track","on-track",
        "on-track","on-track","on-track","on-track","on-track",
        "on-track","on-track","on-track",
        # at-risk
        "at-risk","at-risk","at-risk","at-risk","at-risk",
        "at-risk","at-risk","at-risk","at-risk","at-risk",
        # delayed
        "delayed","delayed","delayed","delayed","delayed",
        "delayed","delayed","delayed","delayed","delayed",
    ])

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)

    with open(MODEL_PATH, "wb") as f:
        pickle.dump(model, f)

    print(" ML Model trained and saved!")
    return model


def load_model():
    """Load model from disk, train if not exists"""
    if not os.path.exists(MODEL_PATH):
        return train_model()
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


def predict_status(progress, tasks_total, tasks_completed, tasks_overdue, days_since_joining):
    """Predict employee status using ML model"""
    model = load_model()
    features = np.array([[progress, tasks_total, tasks_completed, tasks_overdue, days_since_joining]])
    prediction = model.predict(features)[0]
    probabilities = model.predict_proba(features)[0]
    confidence = round(max(probabilities) * 100)
    return prediction, confidence