import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import pickle
import os

def train_model():
    """Train the ML model to predict employee onboarding status"""
    
    print(" Starting model training...")
    
    # Load training data (generated by generate_dummy_data.py)
    if not os.path.exists('training_data.csv'):
        print(" Error: training_data.csv not found!")
        print("Run 'python generate_dummy_data.py' first")
        return
    
    df = pd.read_csv('training_data.csv')
    print(f" Loaded {len(df)} training records")
    
    # Features for prediction
    X = df[['completion_rate', 'days_elapsed', 'overdue_tasks', 'avg_time_per_task']]
    
    # Target variable (what we want to predict)
    y = df['status']
    
    # Split data into training and testing sets (80% train, 20% test)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # Normalize the features (scale to 0-1 range)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Train Random Forest Classifier
    print(" Training Random Forest model...")
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42
    )
    model.fit(X_train_scaled, y_train)
    
    # Evaluate accuracy
    train_accuracy = model.score(X_train_scaled, y_train)
    test_accuracy = model.score(X_test_scaled, y_test)
    
    print(f" Training Accuracy: {train_accuracy * 100:.2f}%")
    print(f" Testing Accuracy: {test_accuracy * 100:.2f}%")
    
    # Save model and scaler
    with open('model.pkl', 'wb') as f:
        pickle.dump(model, f)
    
    with open('scaler.pkl', 'wb') as f:
        pickle.dump(scaler, f)
    
    print(" Model saved as model.pkl")
    print(" Scaler saved as scaler.pkl")
    
    # Show feature importance
    feature_importance = pd.DataFrame({
        'feature': X.columns,
        'importance': model.feature_importances_
    }).sort_values('importance', ascending=False)
    
    print("\n Feature Importance:")
    print(feature_importance.to_string(index=False))
    
    return model, scaler

if __name__ == '__main__':
    train_model()